### ISSUE TITLE
Minor mistake in Comment

### ISSUE THREAD

**Issue by harshit158** [guillaumegenthial/tf_ner#11]
https://github.com/guillaumegenthial/tf_ner/blob/c3284f0f97d7c379579cbd1802de3e8c651478ab/models/chars_conv_lstm_crf/main.py#L96

The comment says "Char LSTM" whereas it should have been "Char CNN". A minor issue, but a confusing one for newbies.

**Comment by guillaumegenthial** [comment]
Fixed, thanks
