### ISSUE TITLE
How to save a model?

### ISSUE THREAD

**Issue by 1049451037** [guillaumegenthial/tf_ner#2]
After training a model, how to avoid retraining for the next time?

**Comment by guillaumegenthial** [comment]
@1049451037 once trained, the weights are saved the `results` directory! Next time you instantiate the same estimator, with the same graph and same `model_dir`, it will reload the weights.

**Comment by gamerrishad** [comment]
Hello @guillaumegenthial what should be the `serving_input_fn` if we really want to use `estimator.export_savedmodel`?? I've created a new issue on this.
