### ISSUE TITLE
Could you provide the training data?

### ISSUE THREAD

**Issue by 1049451037** [guillaumegenthial/tf_ner#3]
As you said, "*Note that the example dataset is here for debugging purposes only and won't be of much use to train an actual model*". However, I really need your training data to use the NER model.

Although I can get them from some datasets like CONLL, I think it is helpful (at least time-saving) not just for me to share the datasets which can be used in your code directly.

**Comment by 1049451037** [comment]
Alright...I find it from [here](https://github.com/synalp/NER/tree/master/corpus/CoNLL-2003)

**Comment by kmonachopoulos** [comment]
@1049451037 still this dataset that you are point to is in a different format ...

**Comment by kmonachopoulos** [comment]
Is there a chance to find CONLL2003 in the same format as in data/example ?
