### ISSUE TITLE
ValueError: max() arg is an empty sequence at line 36

### ISSUE THREAD

**Issue by samhithr** [guillaumegenthial/tf_ner#46]
I am getting this error in main.py while I try to run the program. Has anyone else faced the same issue.

**Comment by gui-li** [comment]
@samhithr Same error here, how did you solve it?

**Comment by samhithr** [comment]
@gui-li  There were blank lines in my data which caused this error. Removing them resolved the issue.

**Comment by gui-li** [comment]
@samhithr Thank you so much, that's really helpful!
