### ISSUE TITLE
how to get top-k best candidate sequences when using CRF for decoding?

### ISSUE THREAD

**Issue by zfyu** [guillaumegenthial/tf_ner#47]
how to get top-k best candidate sequences when using CRF for decoding in tensorflow?

**Comment by guillaumegenthial** [comment]
Hi @zfyu, sorry to tell you that, but you can't! Theoretically you could, but you would need to modify the tensorflow crf implementation so that the dynamic decoding keeps track of the top k at every recurrence step.

**Comment by zfyu** [comment]
Thank you for your suggestion. @guillaumegenthial

**Comment by createmomo** [comment]
> how to get top-k best candidate sequences when using CRF for decoding in tensorflow?

Hi, maybe you can consider re-implement the n-best output algorithm mentioned in this tool by yourself,
https://taku910.github.io/crfpp/

**Comment by zfyu** [comment]
@createmomo 
Thank you very much. I'll try it. BTW, I found that I read your blog ["CRF Layer on the Top of BiLSTM - 1"](https://createmomo.github.io/2017/09/12/CRF_Layer_on_the_Top_of_BiLSTM_1/) a few days ago. What a coincidence! It is very helpful！
